/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuiaDeVendasRouteImport } from './routes/guia-de-vendas'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMoldesRouteImport } from './routes/admin.moldes'
import { Route as AdminSorteioRouteImport } from './routes/admin.sorteio'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeVendasRoute = GuiaDeVendasRouteImport.update({
  id: '/guia-de-vendas',
  path: '/guia-de-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/admin/configuracoes',
  path: '/admin/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMoldesRoute = AdminMoldesRouteImport.update({
  id: '/admin/moldes',
  path: '/admin/moldes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSorteioRoute = AdminSorteioRouteImport.update({
  id: '/admin/sorteio',
  path: '/admin/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/admin/videos',
  path: '/admin/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moldes': typeof AdminMoldesRoute
  '/admin/sorteio': typeof AdminSorteioRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moldes': typeof AdminMoldesRoute
  '/admin/sorteio': typeof AdminSorteioRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/moldes': typeof AdminMoldesRoute
  '/admin/sorteio': typeof AdminSorteioRoute
  '/admin/videos': typeof AdminVideosRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guia-de-vendas'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/moldes'
    | '/admin/sorteio'
    | '/admin/videos'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/guia-de-vendas'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/moldes'
    | '/admin/sorteio'
    | '/admin/videos'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/guia-de-vendas'
    | '/admin/configuracoes'
    | '/admin/login'
    | '/admin/moldes'
    | '/admin/sorteio'
    | '/admin/videos'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuiaDeVendasRoute: typeof GuiaDeVendasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMoldesRoute: typeof AdminMoldesRoute
  AdminSorteioRoute: typeof AdminSorteioRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-vendas': {
      id: '/guia-de-vendas'
      path: '/guia-de-vendas'
      fullPath: '/guia-de-vendas'
      preLoaderRoute: typeof GuiaDeVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/admin/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moldes': {
      id: '/admin/moldes'
      path: '/admin/moldes'
      fullPath: '/admin/moldes'
      preLoaderRoute: typeof AdminMoldesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sorteio': {
      id: '/admin/sorteio'
      path: '/admin/sorteio'
      fullPath: '/admin/sorteio'
      preLoaderRoute: typeof AdminSorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/admin/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuiaDeVendasRoute: GuiaDeVendasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMoldesRoute: AdminMoldesRoute,
  AdminSorteioRoute: AdminSorteioRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
