/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExclusivoRouteImport } from './routes/exclusivo'
import { Route as GuiaDeVendasRouteImport } from './routes/guia-de-vendas'
import { Route as AdminsistemaIndexRouteImport } from './routes/adminsistema.index'
import { Route as AdminsistemaConfiguracoesRouteImport } from './routes/adminsistema.configuracoes'
import { Route as AdminsistemaExclusivoRouteImport } from './routes/adminsistema.exclusivo'
import { Route as AdminsistemaLoginRouteImport } from './routes/adminsistema.login'
import { Route as AdminsistemaMoldesRouteImport } from './routes/adminsistema.moldes'
import { Route as AdminsistemaSorteioRouteImport } from './routes/adminsistema.sorteio'
import { Route as AdminsistemaVideosRouteImport } from './routes/adminsistema.videos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExclusivoRoute = ExclusivoRouteImport.update({
  id: '/exclusivo',
  path: '/exclusivo',
  getParentRoute: () => rootRouteImport,
} as any)
const GuiaDeVendasRoute = GuiaDeVendasRouteImport.update({
  id: '/guia-de-vendas',
  path: '/guia-de-vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaIndexRoute = AdminsistemaIndexRouteImport.update({
  id: '/adminsistema/',
  path: '/adminsistema/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaConfiguracoesRoute =
  AdminsistemaConfiguracoesRouteImport.update({
    id: '/adminsistema/configuracoes',
    path: '/adminsistema/configuracoes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminsistemaExclusivoRoute = AdminsistemaExclusivoRouteImport.update({
  id: '/adminsistema/exclusivo',
  path: '/adminsistema/exclusivo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaLoginRoute = AdminsistemaLoginRouteImport.update({
  id: '/adminsistema/login',
  path: '/adminsistema/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaMoldesRoute = AdminsistemaMoldesRouteImport.update({
  id: '/adminsistema/moldes',
  path: '/adminsistema/moldes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaSorteioRoute = AdminsistemaSorteioRouteImport.update({
  id: '/adminsistema/sorteio',
  path: '/adminsistema/sorteio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminsistemaVideosRoute = AdminsistemaVideosRouteImport.update({
  id: '/adminsistema/videos',
  path: '/adminsistema/videos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exclusivo': typeof ExclusivoRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/adminsistema/configuracoes': typeof AdminsistemaConfiguracoesRoute
  '/adminsistema/exclusivo': typeof AdminsistemaExclusivoRoute
  '/adminsistema/login': typeof AdminsistemaLoginRoute
  '/adminsistema/moldes': typeof AdminsistemaMoldesRoute
  '/adminsistema/sorteio': typeof AdminsistemaSorteioRoute
  '/adminsistema/videos': typeof AdminsistemaVideosRoute
  '/adminsistema/': typeof AdminsistemaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exclusivo': typeof ExclusivoRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/adminsistema/configuracoes': typeof AdminsistemaConfiguracoesRoute
  '/adminsistema/exclusivo': typeof AdminsistemaExclusivoRoute
  '/adminsistema/login': typeof AdminsistemaLoginRoute
  '/adminsistema/moldes': typeof AdminsistemaMoldesRoute
  '/adminsistema/sorteio': typeof AdminsistemaSorteioRoute
  '/adminsistema/videos': typeof AdminsistemaVideosRoute
  '/adminsistema': typeof AdminsistemaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exclusivo': typeof ExclusivoRoute
  '/guia-de-vendas': typeof GuiaDeVendasRoute
  '/adminsistema/configuracoes': typeof AdminsistemaConfiguracoesRoute
  '/adminsistema/exclusivo': typeof AdminsistemaExclusivoRoute
  '/adminsistema/login': typeof AdminsistemaLoginRoute
  '/adminsistema/moldes': typeof AdminsistemaMoldesRoute
  '/adminsistema/sorteio': typeof AdminsistemaSorteioRoute
  '/adminsistema/videos': typeof AdminsistemaVideosRoute
  '/adminsistema/': typeof AdminsistemaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exclusivo'
    | '/guia-de-vendas'
    | '/adminsistema/configuracoes'
    | '/adminsistema/exclusivo'
    | '/adminsistema/login'
    | '/adminsistema/moldes'
    | '/adminsistema/sorteio'
    | '/adminsistema/videos'
    | '/adminsistema/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exclusivo'
    | '/guia-de-vendas'
    | '/adminsistema/configuracoes'
    | '/adminsistema/exclusivo'
    | '/adminsistema/login'
    | '/adminsistema/moldes'
    | '/adminsistema/sorteio'
    | '/adminsistema/videos'
    | '/adminsistema'
  id:
    | '__root__'
    | '/'
    | '/exclusivo'
    | '/guia-de-vendas'
    | '/adminsistema/configuracoes'
    | '/adminsistema/exclusivo'
    | '/adminsistema/login'
    | '/adminsistema/moldes'
    | '/adminsistema/sorteio'
    | '/adminsistema/videos'
    | '/adminsistema/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExclusivoRoute: typeof ExclusivoRoute
  GuiaDeVendasRoute: typeof GuiaDeVendasRoute
  AdminsistemaConfiguracoesRoute: typeof AdminsistemaConfiguracoesRoute
  AdminsistemaExclusivoRoute: typeof AdminsistemaExclusivoRoute
  AdminsistemaLoginRoute: typeof AdminsistemaLoginRoute
  AdminsistemaMoldesRoute: typeof AdminsistemaMoldesRoute
  AdminsistemaSorteioRoute: typeof AdminsistemaSorteioRoute
  AdminsistemaVideosRoute: typeof AdminsistemaVideosRoute
  AdminsistemaIndexRoute: typeof AdminsistemaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exclusivo': {
      id: '/exclusivo'
      path: '/exclusivo'
      fullPath: '/exclusivo'
      preLoaderRoute: typeof ExclusivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guia-de-vendas': {
      id: '/guia-de-vendas'
      path: '/guia-de-vendas'
      fullPath: '/guia-de-vendas'
      preLoaderRoute: typeof GuiaDeVendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/': {
      id: '/adminsistema/'
      path: '/adminsistema'
      fullPath: '/adminsistema/'
      preLoaderRoute: typeof AdminsistemaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/configuracoes': {
      id: '/adminsistema/configuracoes'
      path: '/adminsistema/configuracoes'
      fullPath: '/adminsistema/configuracoes'
      preLoaderRoute: typeof AdminsistemaConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/exclusivo': {
      id: '/adminsistema/exclusivo'
      path: '/adminsistema/exclusivo'
      fullPath: '/adminsistema/exclusivo'
      preLoaderRoute: typeof AdminsistemaExclusivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/login': {
      id: '/adminsistema/login'
      path: '/adminsistema/login'
      fullPath: '/adminsistema/login'
      preLoaderRoute: typeof AdminsistemaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/moldes': {
      id: '/adminsistema/moldes'
      path: '/adminsistema/moldes'
      fullPath: '/adminsistema/moldes'
      preLoaderRoute: typeof AdminsistemaMoldesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/sorteio': {
      id: '/adminsistema/sorteio'
      path: '/adminsistema/sorteio'
      fullPath: '/adminsistema/sorteio'
      preLoaderRoute: typeof AdminsistemaSorteioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adminsistema/videos': {
      id: '/adminsistema/videos'
      path: '/adminsistema/videos'
      fullPath: '/adminsistema/videos'
      preLoaderRoute: typeof AdminsistemaVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExclusivoRoute: ExclusivoRoute,
  GuiaDeVendasRoute: GuiaDeVendasRoute,
  AdminsistemaConfiguracoesRoute: AdminsistemaConfiguracoesRoute,
  AdminsistemaExclusivoRoute: AdminsistemaExclusivoRoute,
  AdminsistemaLoginRoute: AdminsistemaLoginRoute,
  AdminsistemaMoldesRoute: AdminsistemaMoldesRoute,
  AdminsistemaSorteioRoute: AdminsistemaSorteioRoute,
  AdminsistemaVideosRoute: AdminsistemaVideosRoute,
  AdminsistemaIndexRoute: AdminsistemaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
